### ISSUE TITLE
footer in the footer

### ISSUE THREAD

**Issue by enekogk** [enekogk/markuplanguages#1]
I cant put tyhe footer in the footer @zmwebdev

**Comment by zmwebdev** [comment]
@enekogk here one solution:
css.css:
```css
body {
    font: 24px Helvetica;
}

#content {
    display: flex;
    flex-flow: column;
}

#main {
    min-height: 800px;
    margin: 0;
    padding: 0;
    display: flex;
    flex-flow: row;
}

#main > article {
    margin: 4px;
    padding: 5px;
    border: 1px solid black;
    border-radius: 7pt;
    background: white;
    flex: 2 1 60%;
    order: 2;
    
}

#main > nav {
    margin: 4px;
    padding: 5px;
    border: 1px solid black;
    border-radius: 7pt;
    background: white;
    flex: 1 6 4%;
    order: 1;
    /*height: 25%;*/
    float: left;
    
    
}
#main > aside{
    margin: 4px;
    padding: 5px;
    border: 1px solid black;
    border-radius: 7pt;
    background: white;
    flex: 1 6 4%;
    order: 3;
    /*height: 60%;*/
    float: left;
    /*margin-bottom: -300px;*/
}



footer {
    display: block;
    margin: 4px;
    padding: 5px;
    min-height: 50px;
    text-align: center;
}
header{
    display: flex;
    margin: 4px;
    padding: 5px;
    min-height: 100px;

    
    
}



/* Too narrow to support three columns */
@media all and (max-width: 640px) {
    #main, #page {
        flex-direction: column;
    }

    #main > article, #main > nav, #main > {
    /* Return them to document order */
      order: 0;
    }

    #footer {
        order:6;
    }

    #main > header, footer {
        min-height: 300px;
        max-height: 500px;
        
    }
    #main > nav {
        min-height: 400px;
        max-height: 1000px;
        
    }
    
        
    }

    #logo{
        width: 30%;
        margin-left: 30%;
    }
    #bideo{
        width: 60%;
        margin-left: 20%;
    }
    .texto{
        text-align: center;
    }

```

index.html:

```html

<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link href="css.css" rel="stylesheet" type="text/css">
  </head>
  <body>
  
  <header>
    <img src="logo.png" id="logo">
    </header>
    <div id="content">
      <div id="main">
        <article>
          <iframe width="854" height="480" src="https://www.youtube.com/embed/Mg21FgDSs2s" frameborder="0" gesture="media" allowfullscreen id="bideo"></iframe><br>

          <h3 class="texto">Civilizaciones sumergidas Documental national geographic</h3>

          <p>
            Las civilizaciones se diferencian de las sociedades tribales basadas en el parentesco por el predominio del modo de vida urbano 
            (la ciudad, que impone relaciones sociales mas abiertas) y el sedentarismo 
            (que implica el desarrollo de la agricultura y a partir de ella todo tipo de desarrollos tecnologicos y economicos con la division del trabajo, 
            la comercializacion de excedentes y, mas tarde, la industrializacion y la terciarizacion)...<a href="#">Read more</a>
          </p>
        </article>
        <nav> <br>
          <a href="index.html"><img src="home.png" style="width: 10%">HOME</a><br><br>
          <a href="news.html"> <img src="news.png" style="width: 8%">NEWS</a><br><br>
          <a href="media.html"><img src="media.jpg" style="width: 8%">MEDIA</a><br><br>
          <a href="sign.html"><img src="usuario.jpg" style="width: 8%">SIGN UP/LOG IN</a> <br>
        </nav>
        
        <aside>
            <h4>Last News:</h4><br>
            <p>fdsadfsfds</p><br>
            <a href="news.html">More News</a>
        </aside>
      </div>
      <footer>Eneko Garcia - &copy 2017 </footer>
    </div>

  

  
</body></html>
```
